require("sakuexe.plugins-setup")
require("sakuexe.core.options")
require("sakuexe.core.hotkeys")
require("sakuexe.core.colorscheme")
require("sakuexe.plugins.nvim-tree")
require("sakuexe.plugins.lualine")
require("sakuexe.plugins.nvim-cmp")
require("sakuexe.plugins.lsp.mason")
require("sakuexe.plugins.lsp.lspsaga")
require("sakuexe.plugins.lsp.lspconfig")

require("sakuexe.plugins.lsp.null-ls")
